apiVersion: v2
name: bit-broker
appVersion: 0.1
description: Charts for bitbroker deployment. bitbroker is a data brokering platform
version: 1.0.0
home: https://www.bit-broker.io/
icon: https://www.bit-broker.io/images/logo.png
sources:
maintainers:
engine: gotpl
type: application
dependencies:
  - name: ambassador
    version: "6.7.13"
    repository: https://www.getambassador.io
    condition: bbk-ambassador.enabled
    alias: bbk-ambassador
  - name: oathkeeper
    version: "0.12.0"
    repository: https://k8s.ory.sh/helm/charts
    condition: bbk-oathkeeper.enabled
    alias: bbk-oathkeeper
  - name: postgresql
    version: "10.4.6"
    repository: https://charts.bitnami.com/bitnami
    condition: bbk-postgresql.enabled
    alias: bbk-postgresql
  - name: auth-service
    version: "1.0"
    repository: file://../auth-service
    condition: bbk-auth-service.enabled
    alias: bbk-auth-service
  - name: rate-service
    version: "1.0"
    repository: file://../rate-service
    condition: bbk-rate-service.enabled
    alias: bbk-rate-service
  - name: coordinator
    version: "1.0"
    repository: file://../coordinator
    condition: bbk-coordinator.enabled
    alias: bbk-coordinator
  - name: contributor
    version: "1.0"
    repository: file://../contributor
    condition: bbk-contributor.enabled
    alias: bbk-contributor
  - name: consumer
    version: "1.0"
    repository: file://../consumer
    condition: bbk-consumer.enabled
    alias: bbk-consumer
  - name: portal
    version: "1.0"
    repository: file://../portal
    condition: bbk-portal.enabled
    alias: bbk-portal
