apiVersion: v2
name: bit-broker
appVersion: 0.1
description: Charts for bitbroker deployment. bitbroker is a data brokering platform
version: 1.0.0
home: https://www.bit-broker.io/
icon: https://www.bit-broker.io/images/logo.png
sources:
maintainers:
engine: gotpl
type: application
dependencies:
  - name: ambassador
    version: "6.7.2"
    repository: https://www.getambassador.io
    condition: ambassador-bbk.enabled
    alias: ambassador-bbk
  - name: oathkeeper
    version: "0.12.0"
    repository: https://k8s.ory.sh/helm/charts
    condition: oathkeeper-bbk.enabled
    alias: oathkeeper-bbk
  - name: postgresql
    version: "10.4.6"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql-bbk.enabled
    alias: postgresql-bbk
  - name: auth-service
    version: "1.0"
    repository: file://../auth-service
    condition: auth-service.enabled
  - name: rate-service
    version: "1.0"
    repository: file://../rate-service
    condition: rate-service.enabled
  - name: coordinator
    version: "1.0"
    repository: file://../coordinator
    condition: coordinator.enabled
  - name: contributor
    version: "1.0"
    repository: file://../contributor
    condition: contributor.enabled
  - name: consumer
    version: "1.0"
    repository: file://../consumer
    condition: consumer.enabled
  - name: policy
    version: "1.0"
    repository: file://../policy
    condition: consumer.enabled
