## Default values for policy helm templates.

name: policy
group: app

##policy instance count.
replicaCount: 1

##Docker Image values.
docker:
  imageTag: "latest"
  imagePullPolicy: Always
  imagePullSecret: regcred

container:
  name: policy
  port: 8004


## Service configuration values.
service:
  type: ClusterIP
  port: 8004

## Volume definitions.
volume:
  mountPath: /home/node/app/services/policy/logs
  pvc:
    accessMode: ReadWriteOnce
    storage: 4Gi

redis:
  ## Redis image
  imageTag: "6.2.3-alpine"

  ## Whether or not persistence is enabled
  ##
  persistentVolume:
    enabled: false

    ## Redis data Persistent Volume mount root path
    ##
    mountPath: /data

    ## Redis data Persistent Volume size
    ##
    size: 10Gi

    ## Redis data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    # storageClass: "-"
