## Default values for policy helm templates.

name: policy
group: app

##policy instance count.
replicaCount: 1

##policy security context configuration.
securityContext:
  runAsUser: 1392
  fsGroup: 1392

##Docker Image values.
docker:
  imageTag: "latest"
  imagePullPolicy: Always
  imagePullSecret: regcred

container:
  name: policy
  port: 8001


## Service configuration values.
service:
  type: ClusterIP
  port: 8001

## Volume definitions.
volume:
  mountPath: /home/node/app/services/policy/logs
  pvc:
    accessMode: ReadWriteOnce
    storage: 4Gi
