apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "rateservice.labels" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
{{- if or (.Values.global.metrics.enabled) (.Values.metrics.enabled) }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4000"
{{- end }}
    spec:
      preemptionPolicy: PreemptLowerPriority
      securityContext:
        runAsNonRoot: true
        runAsUser: 1999
      imagePullSecrets:
      - name: {{ .Values.docker.imagePullSecret }}
      containers:
      - name: rate-service
        imagePullPolicy: {{ .Values.docker.imagePullPolicy }}
        image: "{{ .Values.docker.registry | default .Values.global.docker.registry }}/bbkr/rate-service:{{ .Values.docker.imageTag }}"
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 4000
        - containerPort: 7000
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
        env:
          - name: SERVER_HTTP_HOST
            value: "0.0.0.0:4000"
          - name: SERVER_GRPC_HOST
            value: "0.0.0.0:7000"
          - name: GO_ENV
            value: "production"
          - name: METRICS_ENABLED
            value: "{{ .Values.metrics.enabled | default .Values.global.metrics.enabled }}"
          - name: POLICY_SERVICE_ENDPOINT
            value: "http://{{ .Release.Name }}-bbk-coordinator:8003/v1/policy/access-all-areas/access_control"
          - name: POLICY_SERVICE_AUTHORIZATION
            value: ""
          - name: POLICY_SERVICE_TIMEOUT
            value: "5"
{{- if (not .Values.redis.ownInstance.enabled) }}
          - name: REDIS_ADDR
            value: "{{ .Release.Name }}-{{ .Chart.Name }}-redis:6379"
          - name: REDIS_PASSWORD
            value: ""
          - name: REDIS_DB
            value: "0"
{{- else }}
          - name: REDIS_ADDR
            value: "{{ .Values.redis.ownInstance.addr }}"
          - name: REDIS_PASSWORD
            value: "{{ .Values.redis.ownInstance.password }}"
          - name: REDIS_DB
            value: "{{ .Values.redis.ownInstance.db }}"
{{- end }}
