apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-service
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rate-service
  template:
    metadata:
      labels:
        app: rate-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
      - name: {{ .Values.docker.imagePullSecret }}
      containers:
      - name: rate-service
        imagePullPolicy: {{ .Values.docker.imagePullPolicy }}
        image: "{{ .Values.docker.registry }}/rate-service:{{ .Values.docker.imageTag }}"
        ports:
        - containerPort: 4000
        - containerPort: 7000
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-rate-service-configmap
        env:
          - name: SERVER_HTTP_HOST
            value: "localhost:4000"
          - name: SERVER_GRPC_HOST
            value: "0.0.0.0:7000"
          - name: GO_ENV
            value: "production"
          - name: REDIS_ADDR
            value: "rate-service-redis:6379"
          - name: REDIS_PASSWORD
            value: ""
          - name: REDIS_DB
            value: "0"
