apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-redis
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
      - name: redis
        image: "redis:{{ .Values.redisImageTag }}"
        ports:
        - containerPort: 6379
{{- if .Values.persistentVolume.enabled }}
        volumeMounts:
          - name: {{ .Release.Name }}-{{ .Chart.Name }}-data
            mountPath: '{{ .Values.persistentVolume.mountPath }}'
      volumes:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-{{ .Chart.Name }}-pvc
{{- end }}
