apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rate-service
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-rate-service
    tier: backend
spec:
  ports:
  - name: http
    protocol: TCP
    port: 4000
    targetPort: 4000
  - name: grpc
    protocol: TCP
    port: 7000
    targetPort: 7000
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-rate-service
