{{- if (not .Values.redis.ownInstance.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-redis
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-redis
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1999
      containers:
      - name: redis
        image: "redis:{{ .Values.redis.imageTag | default .Values.global.redis.imageTag }}"
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 6379
{{- if or (.Values.global.redis.persistentVolume.enabled) (.Values.redis.persistentVolume.enabled) }}
        volumeMounts:
          - name: {{ .Chart.Name }}-redis-data
            mountPath: '{{ .Values.redis.persistentVolume.mountPath | default .Values.global.redis.persistentVolume.mountPath }}'
      volumes:
      - name: {{ .Chart.Name }}-redis-data
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-redis-pvc
{{- end }}
{{- end }}
