{{- if index .Values "bbk-ambassador" "enabled" }}
{{- if .Values.global.gateway.host }}
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-host
  labels:
    {{ include "bitbroker.labels" . }}
spec:
  ambassador_id: {{ index .Values "bbk-ambassador" "env" "AMBASSADOR_ID" }}
  hostname: {{ .Values.global.gateway.host }}
  acmeProvider:
    email: {{ .Values.global.gateway.acmeProvider }}
  tlsSecret:
    name: {{ .Values.global.gateway.tlsSecret }}
  tls:
    min_tls_version: v1.2
{{- end }}
{{- end }}
---
apiVersion: getambassador.io/v2
kind: AuthService
metadata:
  name: authentication
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "bitbroker.labels" . }}
spec:
  ambassador_id: {{ index .Values "bbk-ambassador" "env" "AMBASSADOR_ID" }}
  auth_service: {{ .Release.Name }}-bbk-oathkeeper-api:4456
  timeout_ms: 5000
  failure_mode_allow: false
  path_prefix: "/decisions/bbk"
  allowed_request_headers:
  - 'x-bbk-auth-token'
  allowed_authorization_headers:
  - 'x-bbk-audience'
  - 'x-bbk-rate-uid'
---
apiVersion: getambassador.io/v2
kind: RateLimitService
metadata:
  name: ratelimit
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "bitbroker.labels" . }}
spec:
  ambassador_id: {{ index .Values "bbk-ambassador" "env" "AMBASSADOR_ID" }}
  service: {{ .Release.Name }}-bbk-rate-service:7000
  protocol_version: v2
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: bbk-consumer
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "bitbroker.labels" . }}
spec:
  ambassador_id: {{ index .Values "bbk-ambassador" "env" "AMBASSADOR_ID" }}
  prefix: /consumer/
  rewrite: ""
  service: {{ .Release.Name }}-bbk-consumer:8003
  labels:
    ambassador:
      - consume:
        - remote_address
        - uid:
            header: 'x-bbk-rate-uid'
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: bbk-contributor
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "bitbroker.labels" . }}
spec:
  ambassador_id: {{ index .Values "bbk-ambassador" "env" "AMBASSADOR_ID" }}
  prefix: /contributor/
  rewrite: ""
  service: {{ .Release.Name }}-bbk-contributor:8002
  labels:
    ambassador:
      - contribute:
        - remote_address
        - uid:
            header: 'x-bbk-rate-uid'
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: bbk-coordinator
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "bitbroker.labels" . }}
spec:
  ambassador_id: {{ index .Values "bbk-ambassador" "env" "AMBASSADOR_ID" }}
  prefix: /coordinator/
  rewrite: ""
  service: {{ .Release.Name }}-bbk-coordinator:8001
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: bbk-portal-app
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "bitbroker.labels" . }}
spec:
  ambassador_id: {{ index .Values "bbk-ambassador" "env" "AMBASSADOR_ID" }}
  prefix: /
  service: {{ .Release.Name }}-bbk-portal:3000
  bypass_auth: true
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: bbk-portal-service
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "bitbroker.labels" . }}
spec:
  ambassador_id: {{ index .Values "bbk-ambassador" "env" "AMBASSADOR_ID" }}
  prefix: /service
  service: {{ .Release.Name }}-bbk-portal:8100
  bypass_auth: true
---
{{- if  .Values.global.gateway.certificateIssuer }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-bbk-cluster-issuer
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "bitbroker.labels" . }}
spec:
  acme:
    email: {{ .Values.global.gateway.acmeProvider }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: bbk-cluster-issuer
    solvers:
    - http01:
        ingress:
          class: nginx
      selector: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bbk-acme-challenge-service
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "bitbroker.labels" . }}
spec:
  ports:
  - port: 80
    targetPort: 8089
  selector:
    acme.cert-manager.io/http01-solver: "true"
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: bbk-acme-challenge-service
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "bitbroker.labels" . }}
spec:
  ambassador_id: {{ index .Values "bbk-ambassador" "env" "AMBASSADOR_ID" }}
  prefix: /.well-known/acme-challenge/
  rewrite: ""
  service: {{ .Release.Name }}-bbk-acme-challenge-service
  bypass_auth: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-bbk-certificate
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "bitbroker.labels" . }}
spec:
  secretName: {{ .Values.global.gateway.tlsSecret }}
  issuerRef:
    name: {{ .Release.Name }}-bbk-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - {{ .Values.global.gateway.host }}
{{- end }}
