{{- if index .Values "bbk-ambassador" "enabled" }}
{{- if .Values.global.gateway.host }}
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-host
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  hostname: {{ .Values.global.gateway.host }}
  acmeProvider:
    email: {{ .Values.global.gateway.acmeProvider }}
{{- if  .Values.global.gateway.tlsSecret }}
  tlsSecret:
    name: {{ .Values.global.gateway.tlsSecret }}
{{- end }}
{{- end }}
{{- end }}
---
apiVersion: getambassador.io/v2
kind: AuthService
metadata:
  name: authentication
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  auth_service: {{ .Release.Name }}-bbk-oathkeeper-api:4456
  timeout_ms: 5000
  failure_mode_allow: false
  path_prefix: "/decisions/bbk"
  allowed_request_headers:
  - '{{ .Values.global.headers.authToken }}'
  allowed_authorization_headers:
  - '{{ .Values.global.headers.policy }}'
---
apiVersion: getambassador.io/v2
kind: RateLimitService
metadata:
  name: ratelimit
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  service: {{ .Release.Name }}-rate-service:7000
  protocol_version: v2
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: bbk-consumer
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  prefix: /consumer/
  rewrite: /v1/
  service: {{ .Release.Name }}-bbk-consumer:8001
  labels:
    ambassador:
      - consume:
        - remote_address
        - uid:
            header: '{{ .Values.global.headers.policy }}'
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: bbk-contributor
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  prefix: /contributor/
  rewrite: /v1/
  service: {{ .Release.Name }}-bbk-contributor:8002
  labels:
    ambassador:
      - contribute:
        - remote_address
        - uid:
            header: '{{ .Values.global.headers.policy }}'
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: bbk-coordinator
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  prefix: /coordinator/
  rewrite: /v1/
  service: {{ .Release.Name }}-bbk-coordinator:8003
  labels:
    ambassador:
      - contribute:
        - remote_address
        - uid:
            header: '{{ .Values.global.headers.policy }}'
