{{- if index .Values "bbk-oathkeeper" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Release.Name }}-bbk-oathkeeper-rules'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  "access-rules.json": |
    [{
      "id": "bbk-consumer-auth",
      "match": {
        "url": "<http|https>://<.*>/bbk/consumer/<.*>",
        "methods": ["GET", "HEAD"]
      },
      "authenticators": [
        {
          "handler": "jwt",
          "config": {
            "scope_strategy": "exact",
            "required_scope": ["consumer"],
            "trusted_issuers": ["{{ .Values.global.issuer }}"],
            "allowed_algorithms": ["RS256"],
            "jwks_urls": [
              "http://{{ .Release.Name }}-bbk-auth-service:8080/api/v1/.well-known/jwks.json"
            ],
            "token_from": {
              "header": "x-bbk-auth-token"
            }
          }
        }
      ],
      "authorizer": {
        "handler": "remote",
        "config": {
          "remote": "http://{{ .Release.Name }}-bbk-auth-service:8080/api/v1/token/check",
          "headers": {
            "x-auth-jti": '{{ "{{ print .Extra.jti }}" }}'
          }
        }
      },
      "mutators": [
        {
          "handler": "header",
          "config": {
            "headers": {
              "x-bbk-audience": '{{ "{{ print .Extra.aud }}" }}',
              "x-bbk-rate-uid": '{{ "{{ print (index .Extra.scp 0) }}:{{ print .Extra.aud }}" }}',
            }
          }
        }
      ]
    },
    {
    "id": "bbk-contributor-auth",
    "match": {
      "url": "<http|https>://<.*>/bbk/contributor/<.*>",
      "methods": ["GET", "HEAD", "POST"]
    },
    "authenticators": [
      {
        "handler": "jwt",
        "config": {
          "scope_strategy": "exact",
          "required_scope": ["contributor"],
          "trusted_issuers": ["{{ .Values.global.issuer }}"],
          "allowed_algorithms": ["RS256"],
          "jwks_urls": [
            "http://{{ .Release.Name }}-bbk-auth-service:8080/api/v1/.well-known/jwks.json"
          ],
          "token_from": {
            "header": "x-bbk-auth-token"
          }
        }
      }
    ],
    "authorizer": {
      "handler": "remote",
      "config": {
        "remote": "http://{{ .Release.Name }}-bbk-auth-service:8080/api/v1/token/check",
        "headers": {
          "x-auth-jti": '{{ "{{ print .Extra.jti }}" }}'
        }
      }
    },
    "mutators": [
      {
        "handler": "header",
        "config": {
          "headers": {
            "x-bbk-audience": '{{ "{{ print .Extra.aud }}" }}'
          }
        }
      }
    ]
    },
    {
    "id": "bbk-coordinator-auth",
    "match": {
      "url": "<http|https>://<.*>/bbk/coordinator/<.*>",
      "methods": ["GET", "HEAD", "POST", "PUT", "DELETE"]
    },
    "authenticators": [
      {
        "handler": "jwt",
        "config": {
          "scope_strategy": "exact",
          "required_scope": ["coordinator"],
          "trusted_issuers": ["{{ .Values.global.issuer }}"],
          "allowed_algorithms": ["RS256"],
          "jwks_urls": [
            "http://{{ .Release.Name }}-bbk-auth-service:8080/api/v1/.well-known/jwks.json"
          ],
          "token_from": {
            "header": "x-bbk-auth-token"
          }
        }
      }
    ],
    "authorizer": {
      "handler": "remote",
      "config": {
        "remote": "http://{{ .Release.Name }}-bbk-auth-service:8080/api/v1/token/check",
        "headers": {
          "x-auth-jti": '{{ "{{ print .Extra.jti }}" }}'
        }
      }
    },
    "mutators": [
      {
        "handler": "header",
        "config": {
          "headers": {
            "x-bbk-audience": '{{ "{{ print .Extra.aud }}" }}'
          }
        }
      }
    ]
    }]
{{- end }}
