{{- if index .Values "oathkeeper-bbk" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-oathkeeper-bbk-rules
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  "access-rules.json": |
    [{
      "id": "bbk-consume-auth",
      "match": {
        "url": "<http|https>://<.*>/bbk/consume/<.*>",
        "methods": ["GET", "HEAD"]
      },
      "authenticators": [
        {
          "handler": "jwt",
          "config": {
            "scope_strategy": "exact",
            "required_scope": ["consume"],
            "trusted_issuers": ["{{ .Values.global.issuer }}"],
            "allowed_algorithms": ["RS256"],
            "token_from": {
              "header": "{{ .Values.global.headers.authToken }}"
            }
          }
        }
      ],
      "authorizer": {
        "handler": "allow"
      },
      "mutators": [
        {
          "handler": "hydrator"
        },
        {
          "handler": "header",
          "config": {
            "headers": {
              "{{ .Values.global.headers.policy }}": "{{ .Values.global.policyTemplate }}"
            }
          }
        }
      ]
    },
    {
    "id": "bbk-contribute-auth",
    "match": {
      "url": "<http|https>://<.*>/bbk/contribute/<.*>",
      "methods": ["GET", "HEAD"]
    },
    "authenticators": [
      {
        "handler": "jwt",
        "config": {
          "scope_strategy": "exact",
          "required_scope": ["contribute"],
          "trusted_issuers": ["{{ .Values.global.issuer }}"],
          "allowed_algorithms": ["RS256"],
          "token_from": {
            "header": "{{ .Values.global.headers.authToken }}"
          }
        }
      }
    ],
    "authorizer": {
      "handler": "allow"
    },
    "mutators": [
      {
        "handler": "hydrator"
      },
      {
        "handler": "header",
        "config": {
          "headers": {
            "{{ .Values.global.headers.policy }}": "{{ .Values.global.policyTemplate }}"
          }
        }
      }
    ]
    }]
{{- end }}
