apiVersion: v1
kind: ConfigMap
metadata:
  name: bbk-postgresql-config
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    helm.sh/hook: post-install
data:
  schema.sql: |-
    {{- (.Files.Glob "schema/schema.sql").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-bbk-admin-jti
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    helm.sh/hook: post-install
data:
  ADMIN_JTI: {{ .Values.global.admin.jti | b64enc }}
