apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
  labels:
    {{ include "authservice.labels" . }}
data:
  LOG_LEVEL: "{{ .Values.logLevel }}"
  ISSUER: "{{ .Values.issuer | default .Values.global.issuer }}"
  JWT_DURATION: "{{ .Values.jwt_duration }}"
