apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  LOG_LEVEL: "{{ .Values.logLevel }}"
  ISSUER: "{{ .Values.issuer | default .Values.global.issuer }}"
