apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-auth-service-configmap
  namespace: '{{ .Release.Namespace }}'
data:
  LOG_LEVEL: "{{ .Values.logLevel }}"
  ISSUER: "{{ .Values.issuer }}"
