apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
  namespace: '{{ .Release.Namespace }}'
data:
  LOG_LEVEL: "{{ .Values.logLevel }}"
  ISSUER: "{{ .Values.issuer }}"
