apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
      - name: {{ .Values.docker.imagePullSecret }}
      containers:
      - name: auth-service
        imagePullPolicy: {{ .Values.docker.imagePullPolicy }}
        image: "{{ .Values.docker.registry }}/auth-service:{{ .Values.docker.imageTag }}"
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-auth-service-configmap
          - secretRef:
              name: {{ .Release.Name }}-secret
