apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1999
      imagePullSecrets:
      - name: {{ .Values.docker.imagePullSecret }}
      containers:
      - name: auth-service
        imagePullPolicy: {{ .Values.docker.imagePullPolicy }}
        image: "{{ .Values.docker.registry | default .Values.global.docker.registry }}/bbkr/auth-service:{{ .Values.docker.imageTag }}"
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
          - secretRef:
              name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
