apiVersion: batch/v1
kind: Job
metadata:
  name: auth-service-preinstall-job
  annotations:
    "helm.sh/hook": "pre-install"

spec:
  template:
    spec:
      containers:
        - name: pre-install
          image: {{ .Values.docker.registry }}/auth-service:{{ .Values.docker.imageTag }}
          imagePullPolicy: IfNotPresent

          command: ['npm run --silent create-jwks > /etc/jwks/key'; sleep 5']

      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 0

  backoffLimit: 3
  completions: 1
  Parallelism: 1