{{- if or (.Values.global.metrics.enabled) (.Values.metrics.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-servicemonitor
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "authservice.labels" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-{{ .Chart.Name }}
  endpoints:
    - port: http
{{- end }}
