apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-pre-install-job
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ .Release.Name }}-{{ .Chart.Name }}-pre-install-job
    spec:
      imagePullSecrets:
      - name: {{ .Values.docker.imagePullSecret }}
      restartPolicy: Never
      containers:
      - name: pre-install-job
        imagePullPolicy: Always
        image: {{ .Values.docker.registry }}/auth-service:{{ .Values.docker.imageTag }}
        command: ['npm', 'run', 'check-jwks', '{{ .Values.JWKS }}', '--silent']
