apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-pre-install-job
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "authservice.labels" . }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ .Release.Name }}-{{ .Chart.Name }}-pre-install-job
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1999
      imagePullSecrets:
      - name: {{ .Values.docker.imagePullSecret }}
      restartPolicy: Never
      containers:
      - name: pre-install-job
        imagePullPolicy: Always
        image: {{ .Values.docker.registry | default .Values.global.docker.registry }}/bbkr/auth-service:{{ .Values.docker.imageTag }}
        securityContext:
          allowPrivilegeEscalation: false
        command: ['npm', 'run', 'check-jwks', '{{ .Values.JWKS }}', '--silent']
