apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "authservice.labels" . }}
  annotations:
    helm.sh/hook: pre-install
data:
  JWKS: {{ .Values.JWKS }}
