apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
  namespace: '{{ .Release.Namespace }}'
  labels:
    release: {{ .Release.Name }}-{{ .Chart.Name }}
    heritage: {{ .Release.Service }}
data:
  JWKS: {{ .Values.JWKS }}
