{{- if (not .Values.redis.ownInstance.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-redis
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "authservice.labels" . }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: 6379
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-redis
{{- end }}
