apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8003"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1999
        fsGroup: 1999
      containers:
        - name: coordinator
          image: "{{ .Values.docker.registry | default .Values.global.docker.registry }}/bbkr/coordinator:{{ .Values.docker.imageTag }}"
          imagePullPolicy: {{ .Values.docker.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8003
          env:
            - name: APP_NAME
              value: "Bit-Broker"
            - name: APP_MODE
              value: "standard"
            - name: COORDINATOR_NAME
              value: "Bit-Broker Coordinator Server"
            - name: COORDINATOR_BASE
              value: "http://{{ .Release.Name }}-{{ .Chart.Name }}:8003/v1"
            - name: DATABASE
              value: "postgresql://CREDENTIALS@{{ .Release.Name }}-{{ .Chart.Name }}/bit_broker"
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
