{{- $secret := printf "%s:%s" "bbk_coordinator" (.Values.password | default .Values.global.passwords.coordinator) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  COORDINATOR_USER: {{ $secret | b64enc }}
