apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8003
    targetPort: 8003
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
