name: Release and Publish Helm Chart

on:
  push:
    tags:
      - v*
  pull_request:
    tags:
      - v*

jobs:
  helm_release:
    name: Publish Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Parse tag name
        run: echo "TAG_NAME=$(echo $GITHUB_REF | cut -d / -f 3 | cut -c2-)" >> $GITHUB_ENV

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Add Bitnami Repository
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Add Datawire Repository
        run: helm repo add datawire https://app.getambassador.io

      - name: Add Ory Repository
        run: helm repo add ory https://k8s.ory.sh/helm/charts

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs helm/charts --target-branch main --validate-maintainers=false

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: helm/charts
          config: .cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
