## Docker image
##
docker:
  imageTag: "latest"
  imagePullPolicy: "Always"
  imagePullSecret: "regcred"

  ## If private registry
  ##
  #registry: ""

## Number of replicas
##
replicaCount: 1

## Token's issuer
##
issuer: "bit-broker.io"

## Debug tools
##
logLevel: "info"

## JWKS
##
JWKS: "JWKS"
